### ISSUE TITLE
Are you going to release the frameworks code?

### ISSUE THREAD

**Issue by massih10** [phucty/mtab_tool#3]

**Comment by phucty** [comment]
Hi @massih10 ,

Thank you for your question.

I am sorry for my late reply. 

The development code of the MTab tool is available at [mtab_dev](https://github.com/phucty/mtab_dev)
This is not a release, and no documents as well. 

This repo missed the datasets. Since these are too big (~1.5T) so I could not upload them anywhere, but you can generate them from the dumps of Wikidata, Wikipedia, and DBpedia. 
Refer to `download.sh` in `/data` to get necessary dumps
 and `/api/resources/main.py` to generate local databases. It might take 2-3 weeks to create a completely new database. 

I hope you can use some parts of my implementation.

Thank you.
Regards,

Phuc

**Comment by phucty** [comment]
Closed this issue since no reply. If you have any other requests on source code, please reopen the issue.
